### ISSUE TITLE
uploadFile 上传图片返回的数据格式是怎样的？

### ISSUE THREAD

**Issue by namelzx** [ianho/xing-weapp-editor#5]

**Comment by namelzx** [comment]
已经解决。
感谢分享

**Comment by xhf19940721** [comment]
> 已经解决。
> 感谢分享

返回的数据格式是什么样的啊？遇到这个问题了，求告知谢谢！

**Comment by ianho** [comment]
传入`image-upload-key-chain`参数对应返回格式
如：返回的json数据为`{ image : { url: 'http://xxx.jpg' } }`，则传入`image.url`
可在README中`组件属性`表格中查到
